export default function Footer() {
    return (
        <footer className="w-full bg-gray-950 border-t border-gray-800 mt-20">

            <div className="max-w-7xl mx-auto px-6 py-6 text-center">

                <p className="text-sm text-gray-400 leading-relaxed max-w-4xl mx-auto">

                    Disclaimer: TrustGuard is an AI-assisted claims intelligence and advisory system.
                    The outputs and risk assessments generated by this platform are intended solely
                    to support auditors and investigators in identifying potential anomalies, errors,
                    or indicators of fraud.

                    <br /><br />

                    This system does not provide official rulings, legal judgments, or enforcement
                    decisions. All flagged cases require independent human review and verification
                    before any action is taken. TrustGuard shall not be used as a sole basis for
                    disciplinary, legal, or financial actions against any individual or organization.

                </p>

                <p className="mt-4 text-xs text-gray-500">
                    © {new Date().getFullYear()} TrustGuard. All rights reserved.
                </p>

            </div>
        </footer>
    );
}